# neomikanagi openwrt_main 定制包列表（sync-from-upstream.sh 自动应用）

@ENABLE
docker
dockerd
docker-compose
containerd
fuse-overlayfs
luci-app-dockerman
luci-app-homeproxy
sing-box
lxc
lxc-common
lxc-start
lxc-stop
lxc-destroy
lxc-autostart
lxc-info
lxc-ls
luci-app-lxc
luci-i18n-lxc-zh-cn
kmod-zram
zram-swap
kmod-crypto-zstd
kmod-lib-zstd
libzstd
zstd
usbmuxd
libimobiledevice-utils
openssh-sftp-server
kmod-bluetooth
kmod-btusb
kmod-btsdio
bluez-daemon
bluez-utils
adb

@DISABLE
attendedsysupgrade-common
luci-app-attendedsysupgrade
luci-i18n-attendedsysupgrade-zh-cn
luci-app-samba4
luci-i18n-samba4-zh-cn
samba4-admin
samba4-client
samba4-libs
samba4-server
samba4-utils
ddns-scripts
ddns-scripts-services
luci-app-ddns
luci-i18n-ddns-zh-cn
frpc
frps
luci-app-frpc
luci-app-frps
luci-i18n-frpc-zh-cn
luci-i18n-frps-zh-cn
